[package]
name = "ballistic-deposition"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "2.1.0"
itertools = "0.10.1"
rayon = "1.5.1"
num = "0.4.0"
ndarray = "0.15.3"
csv = "1.1.6"