[package]
name = "ballistic-deposition"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.10.0", features = ["macros"] }
configparser = "2.1.0"
itertools = "0.10.1"