[package]
name = "ballistic-deposition"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.10.0", features = ["macros"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"